// auto-generated by scripts/generate-stories.mjs — launch/teardown a headless Chromium per scenario.
import { Before, After } from '@cucumber/cucumber';
import { chromium } from 'playwright';
import { AppWorld } from './world';

Before(async function (this: AppWorld) {
  this.browser = await chromium.launch({ headless: true });
  this.page = await this.browser.newPage();
});

After(async function (this: AppWorld) {
  await this.page?.close();
  await this.browser?.close();
});
