// auto-generated by scripts/generate-stories.mjs — Cucumber World (per-scenario Playwright browser).
import { World, setWorldConstructor, setDefaultTimeout, type IWorldOptions } from '@cucumber/cucumber';
import type { Browser, Page } from 'playwright';

setDefaultTimeout(30_000);
export const BASE_URL = process.env.BASE_URL ?? 'http://localhost:5173';

export class AppWorld extends World {
  browser!: Browser;
  page!: Page;
  constructor(options: IWorldOptions) {
    super(options);
  }
}
setWorldConstructor(AppWorld);
