// auto-generated by scripts/generate-stories.mjs — Playwright E2E flow for <SignupCard />.
// Runs against the live app (webServer in playwright.config.ts). Selectors are
// derived from the component: field "Email address", submit "Subscribe",
// success via role="status", validation error via role="alert".
import { test, expect } from '@playwright/test';

test.describe('SignupCard flow', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('valid submission shows a success status', async ({ page }) => {
    await page.getByLabel(/Email address/i).fill('alice@example.com');
    await page.getByRole('button', { name: /Subscribe/i }).click();
    await expect(page.getByRole('status')).toBeVisible();
  });

  test('invalid submission surfaces an accessible error', async ({ page }) => {
    await page.getByLabel(/Email address/i).fill('invalid');
    await page.getByRole('button', { name: /Subscribe/i }).click();
    await expect(page.getByRole('alert')).toBeVisible();
  });
});
