// auto-generated by scripts/generate-stories.mjs — reusable steps shared by every generated .feature.
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import { AppWorld, BASE_URL } from '../support/world';

// Escape regex metacharacters so labels like "Email (required)" don't throw.
const rx = (s: string) => new RegExp(s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');

Given('the app is open', async function (this: AppWorld) {
  await this.page.goto(BASE_URL);
});

When('I enter {string} into the {string} field', async function (this: AppWorld, value: string, label: string) {
  await this.page.getByLabel(rx(label)).fill(value);
});

When('I click the {string} button', async function (this: AppWorld, label: string) {
  await this.page.getByRole('button', { name: rx(label) }).click();
});

Then('I see a confirmation message', async function (this: AppWorld) {
  const status = this.page.getByRole('status');
  await status.waitFor({ state: 'visible' });
  assert.ok(await status.isVisible());
});

Then('I see a validation error', async function (this: AppWorld) {
  const alert = this.page.getByRole('alert');
  await alert.waitFor({ state: 'visible' });
  assert.ok(await alert.isVisible());
});
