import type { Meta, StoryObj } from '@storybook/react-vite';
import { INITIAL_VIEWPORTS } from 'storybook/viewport';
import { fn } from 'storybook/test';

import { Button } from './Button';

// auto-generated by scripts/generate-stories.mjs — state matrix.
// States emitted (derived from Button's props): Default, Loading, Disabled, Dark, Mobile, Long.
const meta = {
  title: 'States/Button',
  component: Button,
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
  args: {
    children: 'Button',
    onClick: fn(),
  },
} satisfies Meta<typeof Button>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    children: 'Button',
  },
};

export const Loading: Story = {
  args: {
    children: 'Button',
    onClick: fn(),
    loading: true,
  },
};

export const Disabled: Story = {
  args: {
    children: 'Button',
    onClick: fn(),
    disabled: true,
  },
};

export const Dark: Story = {
  args: {
    children: 'Button',
  },
  globals: { backgrounds: { value: 'dark' } },
  parameters: {
    backgrounds: { options: { dark: { name: 'Dark', value: '#1a1a1a' } } },
  },
};

export const Mobile: Story = {
  args: {
    children: 'Button',
  },
  globals: { viewport: { value: 'iphone6', isRotated: false } },
  parameters: { viewport: { options: INITIAL_VIEWPORTS } },
};

export const Long: Story = {
  args: {
    children: 'This is intentionally long content used to verify how the component handles wrapping, truncation and vertical growth across multiple lines of text',
  },
};
