// auto-generated by scripts/generate-stories.mjs — RTL unit test.
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';

import { Card } from './Card';

describe('Card', () => {
  it('renders without crashing', () => {
    render(<Card title="Card" description="A short supporting description.">Content</Card>);
    expect(screen.getByRole('heading', { name: /Card/i })).toBeTruthy();
  });
});
