import type { Meta, StoryObj } from '@storybook/react-vite';
import { INITIAL_VIEWPORTS } from 'storybook/viewport';

import { Card } from './Card';

// auto-generated by scripts/generate-stories.mjs — state matrix.
// States emitted (derived from Card's props): Default, Empty, Dark, Mobile, Long.
const meta = {
  title: 'States/Card',
  component: Card,
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
} satisfies Meta<typeof Card>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    title: 'Card',
    description: 'A short supporting description.',
    children: 'Content',
  },
};

export const Empty: Story = {
  args: {},
};

export const Dark: Story = {
  args: {
    title: 'Card',
    description: 'A short supporting description.',
    children: 'Content',
  },
  globals: { backgrounds: { value: 'dark' } },
  parameters: {
    backgrounds: { options: { dark: { name: 'Dark', value: '#1a1a1a' } } },
  },
};

export const Mobile: Story = {
  args: {
    title: 'Card',
    description: 'A short supporting description.',
    children: 'Content',
  },
  globals: { viewport: { value: 'iphone6', isRotated: false } },
  parameters: { viewport: { options: INITIAL_VIEWPORTS } },
};

export const Long: Story = {
  args: {
    title: 'Card',
    description: 'A short supporting description.',
    children: 'This is intentionally long content used to verify how the component handles wrapping, truncation and vertical growth across multiple lines of text',
  },
};
