// auto-generated by scripts/generate-stories.mjs — RTL unit test.
import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/react';

import { SignupCard } from './SignupCard';

describe('SignupCard', () => {
  it('renders without crashing', () => {
    const { container } = render(<SignupCard />);
    expect(container.firstChild).toBeTruthy();
  });
});
