import type { Meta, StoryObj } from '@storybook/react-vite';
import { INITIAL_VIEWPORTS } from 'storybook/viewport';
import { fn } from 'storybook/test';

import { SignupCard } from './SignupCard';

// auto-generated by scripts/generate-stories.mjs — state matrix.
// States emitted (derived from SignupCard's props): Default, Dark, Mobile.
const meta = {
  title: 'States/SignupCard',
  component: SignupCard,
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
  args: {
    onSubscribe: fn(),
  },
} satisfies Meta<typeof SignupCard>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {},
};

export const Dark: Story = {
  args: {},
  globals: { backgrounds: { value: 'dark' } },
  parameters: {
    backgrounds: { options: { dark: { name: 'Dark', value: '#1a1a1a' } } },
  },
};

export const Mobile: Story = {
  args: {},
  globals: { viewport: { value: 'iphone6', isRotated: false } },
  parameters: { viewport: { options: INITIAL_VIEWPORTS } },
};
