// auto-generated by scripts/generate-stories.mjs — RTL unit test.
import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import { TextField } from './TextField';

describe('TextField', () => {
  it('renders without crashing', () => {
    render(<TextField label="Label" />);
    expect(screen.getByLabelText('Label')).toBeTruthy();
  });

  it('calls onChange as the user types', async () => {
    const user = userEvent.setup();
    const onChange = vi.fn();
    render(<TextField label="Label" onChange={onChange} />);
    await user.type(screen.getByLabelText('Label'), 'a');
    expect(onChange).toHaveBeenCalled();
  });
});
