import type { Meta, StoryObj } from '@storybook/react-vite';
import { INITIAL_VIEWPORTS } from 'storybook/viewport';
import { fn } from 'storybook/test';

import { TextField } from './TextField';

// auto-generated by scripts/generate-stories.mjs — state matrix.
// States emitted (derived from TextField's props): Default, Disabled, Error, Dark, Mobile, Long.
const meta = {
  title: 'States/TextField',
  component: TextField,
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
  args: {
    label: 'Label',
    onChange: fn(),
  },
} satisfies Meta<typeof TextField>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: 'Label',
  },
};

export const Disabled: Story = {
  args: {
    label: 'Label',
    onChange: fn(),
    disabled: true,
  },
};

export const Error: Story = {
  args: {
    label: 'Label',
    onChange: fn(),
    error: 'Please enter a valid value.',
    value: 'invalid',
  },
};

export const Dark: Story = {
  args: {
    label: 'Label',
  },
  globals: { backgrounds: { value: 'dark' } },
  parameters: {
    backgrounds: { options: { dark: { name: 'Dark', value: '#1a1a1a' } } },
  },
};

export const Mobile: Story = {
  args: {
    label: 'Label',
  },
  globals: { viewport: { value: 'iphone6', isRotated: false } },
  parameters: { viewport: { options: INITIAL_VIEWPORTS } },
};

export const Long: Story = {
  args: {
    label: 'This is intentionally long content used to verify how the component handles wrapping, truncation and vertical growth across multiple lines of text',
  },
};
