import type { Meta, StoryObj } from '@storybook/react-vite';

import { UserList } from './UserList';

const meta = {
  title: 'Components/UserList',
  component: UserList,
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
} satisfies Meta<typeof UserList>;

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * Default render — auto-generated by scripts/generate-stories.mjs.
 *
 * This single story already gives you a render smoke-test and an accessibility
 * (a11y) check for free via the Vitest + Storybook addon. Flesh out `args`, add
 * more named stories, and add a `play` function to assert behaviour
 * (see Button.stories.tsx for a worked example).
 */
export const Default: Story = {
  args: {
    users: [],
  },
};
