// auto-generated by scripts/generate-stories.mjs — RTL unit test.
import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/react';

import { UserList } from './UserList';

describe('UserList', () => {
  it('renders without crashing', () => {
    const { container } = render(<UserList users={[]} />);
    expect(container.firstChild).toBeTruthy();
  });
});
