import type { Meta, StoryObj } from '@storybook/react-vite';
import { INITIAL_VIEWPORTS } from 'storybook/viewport';

import { UserList } from './UserList';

// auto-generated by scripts/generate-stories.mjs — state matrix.
// States emitted (derived from UserList's props): Default, Loading, Error, Dark, Mobile.
const meta = {
  title: 'States/UserList',
  component: UserList,
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
  args: {
    users: [],
  },
} satisfies Meta<typeof UserList>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    users: [],
  },
};

export const Loading: Story = {
  args: {
    users: [],
    loading: true,
  },
};

export const Error: Story = {
  args: {
    users: [],
    error: 'Please enter a valid value.',
  },
};

export const Dark: Story = {
  args: {
    users: [],
  },
  globals: { backgrounds: { value: 'dark' } },
  parameters: {
    backgrounds: { options: { dark: { name: 'Dark', value: '#1a1a1a' } } },
  },
};

export const Mobile: Story = {
  args: {
    users: [],
  },
  globals: { viewport: { value: 'iphone6', isRotated: false } },
  parameters: { viewport: { options: INITIAL_VIEWPORTS } },
};
