// scripts/lib/stories.mjs
// ---------------------------------------------------------------------------
// Shared logic for the "every component needs a story" tooling.
//
//   - check-stories.mjs     uses findComponents() to fail CI on missing stories
//   - generate-stories.mjs  uses findComponents() + storyTemplate() to scaffold
//
// A "component" is any PascalCase .tsx/.jsx module under the scanned root(s)
// that exports a component of the same name. Story files, test files, type
// declarations and a few well-known entry files are ignored.
// ---------------------------------------------------------------------------
import { readdirSync, existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

const COMPONENT_EXT = new Set(['.tsx', '.jsx']);
const STORY_RE = /\.stories\.[jt]sx?$/;
const TEST_RE = /\.(test|spec)\.[jt]sx?$/;
const STORY_EXTS = ['tsx', 'ts', 'jsx', 'js'];

// Basenames that are PascalCase but are not reusable components worth a story.
const DEFAULT_IGNORE = new Set(['App', 'Main', 'Root', 'Index']);

// Marker embedded in every generated story so --force can tell its own
// scaffolds apart from hand-written stories (which it must never overwrite).
export const GENERATED_MARKER = 'auto-generated by scripts/generate-stories.mjs';

const isPascalCase = (name) => /^[A-Z][A-Za-z0-9]*$/.test(name);
const titleCase = (s) => s.replace(/^[a-z]/, (c) => c.toUpperCase());

/** Recursively collect every file under `dir`, skipping dot-dirs / node_modules. */
function walk(dir, acc = []) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc;
  }
  for (const entry of entries) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, acc);
    else acc.push(full);
  }
  return acc;
}

/** Pick sensible default scan roots: src/components if present, else src, else cwd. */
export function defaultRoots(cwd = process.cwd()) {
  const candidates = [path.join(cwd, 'src', 'components'), path.join(cwd, 'src')];
  for (const c of candidates) if (existsSync(c)) return [c];
  return [cwd];
}

/** Does a sibling story file exist next to `<dir>/<name>`? */
function hasStoryFile(dir, name) {
  return STORY_EXTS.some((e) => existsSync(path.join(dir, `${name}.stories.${e}`)));
}

/**
 * Inspect a module's source to learn how its same-named component is exported.
 * Returns 'named' | 'default' | null (null = no matching component export).
 */
export function detectExport(source, name) {
  const n = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  if (new RegExp(`export\\s+(?:async\\s+)?function\\s+${n}\\b`).test(source)) return 'named';
  if (new RegExp(`export\\s+(?:const|let|class)\\s+${n}\\b`).test(source)) return 'named';
  if (new RegExp(`export\\s*\\{[^}]*\\b${n}\\b[^}]*\\}`).test(source)) return 'named';
  if (new RegExp(`export\\s+default\\s+(?:function|class)\\s+${n}\\b`).test(source)) return 'default';
  if (new RegExp(`export\\s+default\\s+${n}\\b`).test(source)) return 'default';
  if (/export\s+default\s+(?:function|class|\()/.test(source)) return 'default';
  return null;
}

/**
 * Best-effort extraction of the *required* props from a `<Name>Props`
 * interface/type so the generator can scaffold args that type-check.
 * Only handles the common single-line member style; anything it can't read is
 * simply omitted (the generated story then renders with no args).
 */
/**
 * Parse ALL members of a `<Name>Props` interface/type into
 * `{ name, type, optional }`. Handles the common single-line member style and
 * skips nested object types. Shared by the story tooling and the platform
 * generators (which need optional props too, not just required ones).
 */
export function parseProps(source, name) {
  const start = source.search(
    new RegExp(`(?:interface|type)\\s+${name}Props\\b[^{]*\\{`)
  );
  if (start === -1) return [];
  const open = source.indexOf('{', start);
  let depth = 0;
  let end = -1;
  for (let i = open; i < source.length; i++) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}' && --depth === 0) {
      end = i;
      break;
    }
  }
  if (end === -1) return [];

  // Strip comments, then split into members at top-level `;`/`,`/member-boundary
  // newlines — so multi-member lines, multi-line union/object types, and members
  // with no trailing semicolon are all parsed correctly.
  const body = source
    .slice(open + 1, end)
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\/\/[^\n]*/g, '');

  const props = [];
  for (const member of splitMembers(body)) {
    const m = member.match(/^\s*(\w+)\s*(\?)?\s*:\s*([\s\S]+?)\s*$/);
    if (!m) continue; // skips method signatures, index sigs, spreads
    const [, propName, optional, type] = m;
    props.push({ name: propName, type: type.replace(/\s+/g, ' ').trim(), optional: !!optional });
  }
  return props;
}

const OPEN = '<([{';
const CLOSE = '>)]}';
// Treat `>` in an arrow `=>` as not closing a generic.
const isClose = (s, i) => CLOSE.includes(s[i]) && !(s[i] === '>' && s[i - 1] === '=');

/** Split an interface body into individual member strings, respecting nesting. */
function splitMembers(body) {
  const members = [];
  let depth = 0;
  let cur = '';
  for (let i = 0; i < body.length; i++) {
    const ch = body[i];
    if (OPEN.includes(ch)) depth++;
    else if (isClose(body, i)) depth = Math.max(0, depth - 1);

    if (depth === 0 && (ch === ';' || ch === ',')) {
      if (cur.trim()) members.push(cur);
      cur = '';
      continue;
    }
    if (depth === 0 && ch === '\n' && memberComplete(cur)) {
      members.push(cur);
      cur = '';
      continue;
    }
    cur += ch;
  }
  if (cur.trim()) members.push(cur);
  return members;
}

/** A member is complete once it has a top-level `:` with a non-empty type after it. */
function memberComplete(s) {
  let depth = 0;
  let colon = -1;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (OPEN.includes(c)) depth++;
    else if (isClose(s, i)) depth = Math.max(0, depth - 1);
    else if (c === ':' && depth === 0 && colon === -1) colon = i;
  }
  return colon !== -1 && s.slice(colon + 1).trim().length > 0;
}

/** The required (non-optional) props only — used by the default-story scaffolder. */
export function requiredProps(source, name) {
  return parseProps(source, name).filter((p) => !p.optional).map(({ name, type }) => ({ name, type }));
}

/** Produce a literal placeholder value for a required prop so the story renders. */
function placeholderFor(prop, componentName) {
  const t = prop.type;
  if (/=>|\bFunction\b/.test(t)) return { value: 'fn()', needsFn: true };
  if (/ReactNode|ReactElement|JSX\.Element|ReactChild/.test(t)) {
    return { value: `'${prop.name === 'children' ? componentName : titleCase(prop.name)}'` };
  }
  const literal = t.match(/'([^']*)'/);
  if (/\|/.test(t) && literal) return { value: `'${literal[1]}'` };
  if (/\bstring\b/.test(t)) return { value: `'${titleCase(prop.name)}'` };
  if (/\bnumber\b/.test(t)) return { value: '0' };
  if (/\bboolean\b/.test(t)) return { value: 'false' };
  if (literal) return { value: `'${literal[1]}'` };
  return { value: 'null as never', todo: true }; // typechecks; flagged for the author
}

/**
 * Find every component under `roots`, each tagged with whether it already has a
 * sibling story. `ignore` is a set/array of extra basenames to skip.
 */
export function findComponents(roots, { ignore = [] } = {}) {
  const ignoreSet = new Set([...DEFAULT_IGNORE, ...ignore]);
  const seen = new Set();
  const components = [];

  for (const root of roots) {
    for (const file of walk(root)) {
      if (seen.has(file)) continue;
      const ext = path.extname(file);
      if (!COMPONENT_EXT.has(ext)) continue;
      if (STORY_RE.test(file) || TEST_RE.test(file)) continue;
      const name = path.basename(file, ext);
      if (!isPascalCase(name) || ignoreSet.has(name)) continue;

      let source;
      try {
        source = readFileSync(file, 'utf8');
      } catch {
        continue;
      }
      const exportType = detectExport(source, name);
      if (!exportType) continue; // PascalCase file that isn't actually a component

      seen.add(file);
      const dir = path.dirname(file);
      components.push({
        file,
        dir,
        name,
        exportType,
        source,
        hasStory: hasStoryFile(dir, name),
      });
    }
  }
  components.sort((a, b) => a.file.localeCompare(b.file));
  return components;
}

/** Render a default *.stories.tsx for a component descriptor from findComponents(). */
export function storyTemplate(component) {
  const { name, exportType, source } = component;
  const importLine =
    exportType === 'default' ? `import ${name} from './${name}';` : `import { ${name} } from './${name}';`;

  const required = requiredProps(source, name);
  let needsFn = false;
  let todo = false;
  const argLines = required.map((p) => {
    const ph = placeholderFor(p, name);
    needsFn = needsFn || !!ph.needsFn;
    todo = todo || !!ph.todo;
    return `    ${p.name}: ${ph.value},${ph.todo ? ' // TODO: provide a real value' : ''}`;
  });

  const argsBlock = argLines.length ? `\n  args: {\n${argLines.join('\n')}\n  },\n` : '';
  const fnImport = needsFn ? `import { fn } from 'storybook/test';\n` : '';
  const todoNote = todo
    ? ' *\n * NOTE: some args were scaffolded as `null as never` — fill in real values.\n'
    : '';

  return `import type { Meta, StoryObj } from '@storybook/react-vite';
${fnImport}
${importLine}

const meta = {
  title: 'Components/${name}',
  component: ${name},
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
} satisfies Meta<typeof ${name}>;

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * Default render — ${GENERATED_MARKER}.
 *
 * This single story already gives you a render smoke-test and an accessibility
 * (a11y) check for free via the Vitest + Storybook addon. Flesh out \`args\`, add
 * more named stories, and add a \`play\` function to assert behaviour
 * (see Button.stories.tsx for a worked example).
${todoNote} */
export const Default: Story = {${argsBlock}};
`;
}

/** Parse shared CLI flags: positional roots, --ignore=A,B, --force. */
export function parseArgs(argv) {
  const roots = [];
  const ignore = [];
  let force = false;
  for (const arg of argv) {
    if (arg === '--force' || arg === '-f') force = true;
    else if (arg.startsWith('--ignore=')) ignore.push(...arg.slice('--ignore='.length).split(',').filter(Boolean));
    else if (!arg.startsWith('-')) roots.push(path.resolve(arg));
  }
  return { roots, ignore, force };
}
