# auto-generated by scripts/generate-stories.mjs
Feature: SignupCard flow
  As a user of the app
  I want the SignupCard form to validate and submit
  So that I get clear success and error feedback

  Background:
    Given the app is open

  Scenario: A valid submission shows a confirmation
    When I enter "ada@example.com" into the "Email address" field
    And I click the "Subscribe" button
    Then I see a confirmation message

  Scenario: An invalid submission shows a validation error
    When I enter "invalid" into the "Email address" field
    And I click the "Subscribe" button
    Then I see a validation error
